build:
	docker build -t tgbot .
run:
	docker run -d -p 3000:3000 --name tgbot --rm tgbot
# Makefile для energyUpdate

build:
    docker build -t energy-update-bot . # Используйте символ табуляции в начале этой строки

run:
    docker run -d -p 3000:3000 --name energy-update-bot energy-update-bot # Здесь тоже должна быть табуляция
